// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKFF3deBzpSPQbJtDAwLpdwwMgrbVo-t8',
    appId: '1:186094595183:web:ed8758ef4da647f446719a',
    messagingSenderId: '186094595183',
    projectId: 'arcana-forge',
    authDomain: 'arcana-forge.firebaseapp.com',
    databaseURL: 'https://arcana-forge-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'arcana-forge.firebasestorage.app',
    measurementId: 'G-WRZVXKSRYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPgDpdB8d-Qxzjm6-vPy2Cf-oDWCsBmvM',
    appId: '1:186094595183:android:7234746c03e1016446719a',
    messagingSenderId: '186094595183',
    projectId: 'arcana-forge',
    databaseURL: 'https://arcana-forge-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'arcana-forge.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo3pkF9cpFGvlslV1PQr6Plc6zIEsqvGs',
    appId: '1:186094595183:ios:dfbf761adf0f567546719a',
    messagingSenderId: '186094595183',
    projectId: 'arcana-forge',
    databaseURL: 'https://arcana-forge-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'arcana-forge.firebasestorage.app',
    iosBundleId: 'com.example.arcanaForge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo3pkF9cpFGvlslV1PQr6Plc6zIEsqvGs',
    appId: '1:186094595183:ios:dfbf761adf0f567546719a',
    messagingSenderId: '186094595183',
    projectId: 'arcana-forge',
    databaseURL: 'https://arcana-forge-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'arcana-forge.firebasestorage.app',
    iosBundleId: 'com.example.arcanaForge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKFF3deBzpSPQbJtDAwLpdwwMgrbVo-t8',
    appId: '1:186094595183:web:d0353e37efbb51f046719a',
    messagingSenderId: '186094595183',
    projectId: 'arcana-forge',
    authDomain: 'arcana-forge.firebaseapp.com',
    databaseURL: 'https://arcana-forge-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'arcana-forge.firebasestorage.app',
    measurementId: 'G-RC14QY2XE9',
  );
}
